receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  docker_stats:

processors:
  gnmipath:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  gnmi:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [gnmipath]
      exporters: [gnmi]